### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ItzBenoitXD** [AronikTV/coin-earning-ctrlpanel#9]
hey, this is a stupid issue but how do you set this up? https://github.com/AronikTV/coin-earning-ctrlpanel/blob/main/install.md#step-4-configure-the-variables-clickcoins
i'm currently trying to understand how it work

**Comment by ItzBenoitXD** [comment]
this was supposed to be in discussions, yikes

**Comment by AronikTV** [comment]
Haha sadly I don't have any idea since I didn't made the clickcoins  way @Lishan778 can help you out ^^

**Comment by ItzBenoitXD** [comment]
oh ok

**Comment by Lishan778** [comment]
@ItzBenoitXD it uses Direct link so when user clicks it shows ads and user gets coin

**Comment by ItzBenoitXD** [comment]
> @ItzBenoitXD it uses Direct link so when user clicks it shows ads and user gets coin  

does it like support external links like shrinke.us or no 
and how do you setup a link to work with this

**Comment by Lishan778** [comment]
> > @ItzBenoitXD it uses Direct link so when user clicks it shows ads and user gets coin
> 
> does it like support external links like shrinke.us or no and how do you setup a link to work with this

no clue on whats a shrink.us but as long as its a link it works

**Comment by ItzBenoitXD** [comment]
it's a link shortner but it should work I guess

**Comment by AronikTV** [comment]
Solved ✅
